---
#------------------------------------------------------------------------------
# Description: Playbook to perform 'yum update' on selected hosts.
#        NOTE: This playbook will also reboot hosts if kernel is updated.
#------------------------------------------------------------------------------

- name: Performing yum update on host(s)
  hosts: group1
  become: yes
  any_errors_fatal: false

  ##########################################################
  # Send notification email at start of change to app teams
  ##########################################################
  pre_tasks:
    - mail:
        subject: 'OS patching for weblogic server is beginning now.'
        from: 'svc_cls@brillio.com'
        body: 'Automated OS patching for weblogic is beginning now.'
        to: 'kishore.reddy@brillio.com'
        charset: utf8
      delegate_to: localhost
      tags: mail

  ##########################################################
  # Check Disk Space Usage
  ##########################################################
   - name: Check Disk Space Usage
     hosts: srv1.example.com
     tasks:
          - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space

  ##########################################################
  # Print Demo Message from Logs
  ##########################################################
    # Print as title
    - name: "tower_response=>{{ tower_response | to_json }}<="
      debug:
        msg: "Dummy message"

  #########################################################
  # Execute update procedures
  #########################################################
  roles:
    - { role: pre_update, become: yes }
    - { role: yum_update, become: yes }
    - { role: post_update, become: yes }

  ##########################################################
  # Send notifiction of completion
  ##########################################################
  post_tasks:
    - mail:
        subject: 'OS patching for weblogic has completed.'
        from: 'svc_cls@brillio.com'
        body: "Automated OS patching for weblogic has completed."
        to: 'kishore.reddy@brillio.com'
        charset: utf8
      delegate_to: localhost
      tags: mail 


 